[site]
name = "The Robotics Book"
style = "book"
icon = "media/favicon.ico"

[menu]
names = ["Home", "About", "Authors", "License"]
links = ["/", "/about", "/authors", "/license"]

[media]
include = []
